
#include "gpio.h"

/*
	NOTE: GPIO16 has no name and func
*/

#define NM_NAME1	PERIPHS_IO_MUX_GPIO5_U
#define NM_NAME2	PERIPHS_IO_MUX_GPIO4_U
#define NM_NAME3	PERIPHS_IO_MUX_GPIO0_U
#define NM_NAME4	PERIPHS_IO_MUX_GPIO2_U
#define NM_NAME5	PERIPHS_IO_MUX_MTMS_U
#define NM_NAME6	PERIPHS_IO_MUX_MTDI_U
#define NM_NAME7	PERIPHS_IO_MUX_MTCK_U
#define NM_NAME8	PERIPHS_IO_MUX_MTDO_U
#define NM_NAME9	PERIPHS_IO_MUX_U0RXD_U
#define NM_NAME10	PERIPHS_IO_MUX_U0TXD_U
#define NM_NAME_LED	PERIPHS_IO_MUX_GPIO2_U

#define NM_FUNC1	FUNC_GPIO5
#define NM_FUNC2	FUNC_GPIO4
#define NM_FUNC3	FUNC_GPIO0
#define NM_FUNC4	FUNC_GPIO2
#define NM_FUNC5	FUNC_GPIO14
#define NM_FUNC6	FUNC_GPIO12
#define NM_FUNC7	FUNC_GPIO13
#define NM_FUNC8	FUNC_GPIO15
#define NM_FUNC9	FUNC_GPIO3
#define NM_FUNC10	FUNC_GPIO1
#define NM_FUNC_LED	FUNC_GPIO2

#define NM_BIT1	BIT5
#define NM_BIT2	BIT4
#define NM_BIT3	BIT0
#define NM_BIT4	BIT2
#define NM_BIT5	BIT14
#define NM_BIT6	BIT12
#define NM_BIT7	BIT13
#define NM_BIT8	BIT15
#define NM_BIT9	BIT3
#define NM_BIT10	BIT1
#define NM_BIT_LED	BIT2
